spring:
  datasource:
    url: jdbc:sqlite:./data/pcm-kms.db
    driver-class-name: org.sqlite.JDBC

kms:
  datasource:
    mode: sqlite
    url: jdbc:sqlite:./data/pcm-kms.db
  cache:
    type: local
