spring:
  application:
    name: pcm-kms-server
  profiles:
    active: sqlite
  flyway:
    enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

kms:
  datasource:
    mode: sqlite
    url: jdbc:sqlite:./data/pcm-kms.db
  cache:
    type: local
  security:
    strict-sign: false
    request-expire-seconds: 300
