FROM node:18-alpine AS build
WORKDIR /app
COPY pcm-kms-admin-ui/package.json pcm-kms-admin-ui/package-lock.json ./
RUN npm install
COPY pcm-kms-admin-ui/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
